### ISSUE TITLE
Add index with possible modulus

### ISSUE THREAD

**Issue by gabrieljones** [ctsrc/Base256#2]
Most uncompressed byte streams will have lots of repeats, this will lead to another kind of "lose track of where you are while typing".

A simple remedy to avoid this would be to add the byte index to each byte before encoding and then subtract it out when decoding.
The index could be modulo 8 or 256 or whatever. Not sure why, but my intuition says modulus is a good idea here.

The start word could even be the initial index.

I understand if this adds too much complexity to an otherwise simple solution.

**Comment by ctsrc** [comment]
Hi, thank you for your input and apologies for only getting back to you on this just now 😅

I recently learned of an encoding called the PGP Word List, which remedies the stated problem in a manner similar to what you are suggesting.

Basically, what the PGP Word List does is that instead of having a single list of 256 words, it has two different word lists of 256 words each. Every even position byte gets encoded using one wordlist, and every odd position byte gets encoded using the other word list.

I have added the PGP Word List to the utility and made it the default encoding. The old encoding remains available as well, for backward compatibility.

With that, I consider this issue resolved and am closing it. Hopefully you agree :)

**Comment by mentalisttraceur** [comment]
One other relevant idea for the pot: you could use formatting to help users not lose track.

For example, let's say you print five words per line - you can then capitalize (or italicize, or color, or whatever, depending on what you've got available) every sixth word, resulting in a visual pattern like this:

```
foo foo foo foo foo
FOO foo foo foo foo
foo FOO foo foo foo
foo foo FOO foo foo
foo foo foo FOO foo
foo foo foo foo FOO
foo foo foo foo foo
...
```

I think that gives you a big multiplier to how long you can go for the same effort without losing track. Then you can throw in extra blank lines, again at a pace which *mismatches* the cadence of the all-caps words:


```
foo foo foo foo foo
FOO foo foo foo foo
foo FOO foo foo foo
foo foo FOO foo foo
foo foo foo FOO foo
foo foo foo foo FOO
foo foo foo foo foo

FOO foo foo foo foo
foo FOO foo foo foo
foo foo FOO foo foo
foo foo foo FOO foo
foo foo foo foo FOO
foo foo foo foo foo
FOO foo foo foo foo

foo FOO foo foo foo
foo foo FOO foo foo
foo foo foo FOO foo
foo foo foo foo FOO
foo foo foo foo foo
FOO foo foo foo foo
foo FOO foo foo foo

foo foo FOO foo foo
foo foo foo FOO foo
foo foo foo foo FOO
foo foo foo foo foo
FOO foo foo foo foo
foo FOO foo foo foo
foo foo FOO foo foo

foo foo foo FOO foo
foo foo foo foo FOO
foo foo foo foo foo
...
```

Which gives you another multiplier. Every time you layer in one more, the number of words before the overall visual pattern repeats is multiplied, so it grows pretty fast.
